server:
  port: 3577

# swagger 3.0配置
#config:
#  swagger3:
#    flag: true
#  # swagger3.0配置（不添加会报错）
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher


#
#
#    <select id="getAllTable" resultType="map">
#    SELECT TABLE_NAME, TABLE_COMMENT FROM `information_schema`.`tables` WHERE TABLE_SCHEMA = #{dataBase} ORDER BY TABLE_NAME;
#    </select>
#
#    <select id="getTableColumnInfo" resultType="map">
#    select
#    COLUMN_NAME,
#    COLUMN_COMMENT,
#    DATA_TYPE,
#    CHARACTER_MAXIMUM_LENGTH,
#    IS_NULLABLE,
#    COLUMN_DEFAULT,
#    COLUMN_KEY
#    FROM
#    INFORMATION_SCHEMA.COLUMNS
#    WHERE
#    TABLE_SCHEMA = #{dataBase}
#    and
#    TABLE_NAME = #{tableName};
#    </select>
#
#    <select id="getTableCount" resultType="java.lang.Integer" parameterType="java.lang.String">
#    SELECT count(TABLE_NAME)
#    FROM information_schema.TABLES
#    WHERE TABLE_SCHEMA = #{dataBase};
#    </select>