server:
  port: 3577

# swagger 3.0配置
config:
  swagger3:
    flag: true

spring:
  aop:
    proxy-target-class: true  #true为使用CGLIB代理,AOP动态代理
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?test
    username: root
    password: root
    dataType: mysql  # 可选值 mysql oracle sqlserver postgresql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-while-idle: false
      validation-query: select 1

    # swagger3.0配置（不添加会报错）
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 数据库类型配置
datatype:
  MySQL:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{IP}:{port}/{database}
  clickhouse:
    driverClassName: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://{IP}:{port}/{database}
  SQL Server:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://{IP}:{port};DatabaseName={database}
  Postgre SQL:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://{IP}:{port}/{database}

# mybatis
mybatis-flex:
  mapper-locations: classpath*:com/pzy/codegenerator/**/xml/*Mapper.xml,classpath*:com/pzy/codegenerator/**/**/xml/*Mapper.xml,classpath*:com/pzy/codegenerator/**/**/**/xml/*Mapper.xml
